server:
  port: 51804
spring:
  application:
    name: leadnews-search
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
#      username: root
#      password: 123456
      host: 127.0.0.1
      port: 27017
      database: leadnews-history
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.200.130:8848
#      config:
#        server-addr: 192.168.200.130:8848
#        file-extension: yml
  rabbitmq:
    host: 192.168.44.128
    port: 5672
#    virtual-host: /son
    username: admin
    password: admin
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual # 消费者确认
#        retry:
#          enabled: true # 开启消费者本地重试，重试后默认会reject，丢弃消息
#          initial-interval: 2000ms
#          multiplier: 1
#          max-attempts: 3
#    connection-timeout: 1s #设置MQ的连接超时时间为1s
#    template:
#      retry:
#        enabled: true
#        initial-interval: 1000ms #重试间隔
#        multiplier: 1
#        max-attempts: 3
minio:
  accessKey: ${MINIO_ACCESS_KEY:minio}
  secretKey: ${MINIO_SECRET_KEY:minio123}
  bucket: ${MINIO_BUCKET:leadnews}
  endpoint: ${MINIO_ENDPOINT:http://127.0.0.1:9000}
  readPath: ${MINIO_READ_PATH:http://127.0.0.1:9000}

elasticsearch:
  host: 192.168.44.128
  port: 9200

