server:
  port: 51804
spring:
  application:
    name: leadnews-search
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
#      username: root
#      password: 123456
      host: 127.0.0.1
      port: 27017
      database: leadnews-history
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.200.130:8848
#      config:
#        server-addr: 192.168.200.130:8848
#        file-extension: yml
  minio:
  accessKey: ${MINIO_ACCESS_KEY:minio}
  secretKey: ${MINIO_SECRET_KEY:minio123}
  bucket: ${MINIO_BUCKET:leadnews}
  endpoint: ${MINIO_ENDPOINT:http://127.0.0.1:9000}
  readPath: ${MINIO_READ_PATH:http://127.0.0.1:9000}

elasticsearch:
  host: 192.168.44.128
  port: 9200

