server:
  port: 51804
spring:
  application:
    name: leadnews-search
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
#      username: root
#      password: 123456
      host: 127.0.0.1
      port: 27017
      database: leadnews-history
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.200.130:8848
#      config:
#        server-addr: 192.168.200.130:8848
#        file-extension: yml

elasticsearch:
  host: ${ES_HOST:192.168.44.128}
  port: ${ES_PORT:9200}
  article:
    index: ${ES_ARTICLE_INDEX:app_info_article}

