minio:
  accessKey: ${MINIO_ACCESS_KEY:minio}
  secretKey: ${MINIO_SECRET_KEY:minio123}
  bucket: ${MINIO_BUCKET:leadnews}
  endPoint: ${MINIO_ENDPOINT:http://localhost:9005}
  readPath: ${MINIO_READ_PATH:http://localhost:9005}
#spring:
#  rabbitmq:
#    host: 47.104.68.187
#    port: 5672
#    virtual-host: /son
#    username: son
#    password: 123
#    listener:
#      simple:
#        prefetch: 1
#        acknowledge-mode: auto # 消费者确认
#        retry:
#          enabled: true # 开启消费者本地重试，重试后默认会reject，丢弃消息
#          initial-interval: 2000ms
#          max-attempts: 2
#          multiplier: 1
