minio:
  accessKey: minio
  secretKey: minio123
  bucket: leadnews
  endPoint: http://localhost:9005
  readPath: http://localhost:9005
#spring:
#  rabbitmq:
#    host: 47.104.68.187
#    port: 5672
#    virtual-host: /son
#    username: son
#    password: 123
#    listener:
#      simple:
#        prefetch: 1
#        acknowledge-mode: auto # 消费者确认
#        retry:
#          enabled: true # 开启消费者本地重试，重试后默认会reject，丢弃消息
#          initial-interval: 2000ms
#          max-attempts: 2
#          multiplier: 1
