server:
  port: 51802
spring:
  application:
    name: leadnews-article
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/leadnews_article?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      retries: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
  rabbitmq:
    #    host: 192.168.44.128 #rabbitMQ的ip地址
    host: 192.168.44.128 #rabbitMQ的ip地址
    port: 5672 #端口
#    virtual-host: /son
    username: admin
    password: admin
    connection-timeout: 5000ms #设置MQ的连接超时时间为1s
    template:
      retry:
        enabled: true
        initial-interval: 1000ms #重试间隔
        multiplier: 1
        max-attempts: 2
    publisher-confirm-type: correlated
  freemarker:
    suffix: .ftl               #指定Freemarker模板文件的后缀名
    template-loader-path: classpath:/templates
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: 123456
      connect-timeout: 10000ms
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.heima.model.article.pojos

minio:
  accessKey: minio
  secretKey: minio123
  bucket: leadnews
  endpoint: http://127.0.0.1:9000
  readPath: http://127.0.0.1:9000

aliyun:
  oss:
    accessKeyId: ${ALIBABA_RAM_ACCESS_KEY}
    accessKeySecret: ${ALIBABA_RAM_ACCESS_SECRET}
    endpoint: http://oss-cn-beijing.aliyuncs.com
    host: https://zhuri-leadnews.oss-cn-beijing.aliyuncs.com
    bucket: zhuri-leadnews
    dir: material/
    expireTime: 300

kafka:
  hosts: 127.0.0.1:9092
  group: ${spring.application.name}

