export default {
    tabTitles: [{title: '关注', id:'__follow__'},
        {title: '综合',id:'__all__'},
        {title: '后端',id:1},
        {title: '前端',id:2},
        {title: 'Android',id:3},
        {title: 'iOS',id:4},
        {title: '人工智能',id:6},
        {title: '开发工具',id:5},
        {title: '代码人生',id:0},
        {title: '阅读',id:'__latest__'},
        {title: '排行榜',id:'__hot__'}
    ],
    tabStyles: {
        bgColor: '#FFFFFF',
        titleColor: '#9b9b9b',
        activeTitleColor: '#3D3D3D',
        activeBgColor: '#FFFFFF',
        isActiveTitleBold: true,
        iconWidth: 70,
        iconHeight: 70,
        width: 120,
        height: 80,
        fontSize: 24,
        hasActiveBottom: true,
        activeBottomColor: '#3194ff',
        activeBottomHeight: 6,
        activeBottomWidth: 36,
        textPaddingLeft: 10,
        textPaddingRight: 10,
        normalBottomColor: 'rgba(0,0,0,0.4)',
        normalBottomHeight: 2,
        hasRightIcon: false,
        rightOffset: 100
    }
}
