#全局端口定义server:
# 全局字符集设置
spring:
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  aop:
    proxy-target-class: true
server:
  tomcat:
    uri-encoding: utf-8
bailian:
  dashscope:
    api-key: ${DASH_SCOPE_API_KEY}
    api-host: ${DASH_SCOPE_API_HOST}

