export const courseMockData = {
  courses: [
    { id: 1, title: 'Vue3 完全指南', subtitle: '从零开始掌握 Vue3 组合式 API', description: '本课程将带你从零开始学习 Vue3 的核心概念，包括组合式 API、响应式系统、组件通信等。通过大量实战案例，帮助你快速掌握 Vue3 开发技能。', coverImage: '/static/images/avatar_head_1.png', authorId: 1, authorName: '张三', authorAvatar: '', price: 49.00, originalPrice: 99.00, categoryId: 2, chapterCount: 8, studyCount: 1256, estimatedHours: 8.5 },
    { id: 2, title: 'Spring Boot 实战', subtitle: '构建企业级后端服务', description: '深入学习 Spring Boot 的核心特性，包括自动配置、数据访问、安全认证、微服务架构等。通过完整的项目实战，让你具备独立开发后端系统的能力。', coverImage: '/static/images/avatar_head_2.png', authorId: 2, authorName: '李四', authorAvatar: '', price: 69.00, originalPrice: 129.00, categoryId: 1, chapterCount: 12, studyCount: 2341, estimatedHours: 15.0 },
    { id: 3, title: 'Python 数据分析', subtitle: '从入门到精通', description: '掌握 Python 数据分析的核心技能，包括 NumPy、Pandas、Matplotlib 等库的使用，以及数据清洗、可视化、机器学习入门等内容。', coverImage: '/static/images/avatar_head_3.png', authorId: 3, authorName: '王五', authorAvatar: '', price: 39.00, originalPrice: 79.00, categoryId: 5, chapterCount: 10, studyCount: 892, estimatedHours: 10.0 },
    { id: 4, title: 'React Native 跨平台开发', subtitle: '一套代码构建多端应用', description: '学习 React Native 的核心概念和开发技巧，掌握组件开发、导航、状态管理、原生模块调用等技能，实现真正的跨平台开发。', coverImage: '/static/images/avatar_head_4.png', authorId: 4, authorName: '赵六', authorAvatar: '', price: 59.00, originalPrice: 109.00, categoryId: 3, chapterCount: 9, studyCount: 567, estimatedHours: 12.0 },
    { id: 5, title: 'TypeScript 完全手册', subtitle: '类型安全的 JavaScript', description: '全面学习 TypeScript 的类型系统、高级特性和最佳实践，让你的代码更加健壮、可维护。适合有一定 JavaScript 基础的开发者。', coverImage: '/static/images/avatar_head_5.png', authorId: 5, authorName: '孙七', authorAvatar: '', price: 29.00, originalPrice: 59.00, categoryId: 2, chapterCount: 6, studyCount: 1890, estimatedHours: 6.0 },
    { id: 6, title: 'Docker 容器化实战', subtitle: '容器技术从入门到实践', description: '学习 Docker 容器技术的核心概念，包括镜像构建、容器管理、Dockerfile 编写、Docker Compose 编排等内容。', coverImage: '/static/images/avatar_head_6.png', authorId: 6, authorName: '周八', authorAvatar: '', price: 35.00, originalPrice: 69.00, categoryId: 6, chapterCount: 7, studyCount: 789, estimatedHours: 7.5 },
    { id: 7, title: '算法与数据结构', subtitle: '程序员必备核心技能', description: '系统学习常用的数据结构和算法，包括数组、链表、树、图、排序、查找等。通过大量练习题，提升你的编程能力和面试成功率。', coverImage: '/static/images/avatar_head_7.png', authorId: 7, authorName: '吴九', authorAvatar: '', price: 59.00, originalPrice: 99.00, categoryId: 1, chapterCount: 15, studyCount: 3210, estimatedHours: 20.0 },
    { id: 8, title: '代码整洁之道', subtitle: '写出高质量代码的艺术', description: '学习代码整洁的原则和实践，包括命名规范、函数设计、类设计、错误处理等。让你的代码更加清晰、易读、易维护。', coverImage: '/static/images/avatar_head_8.png', authorId: 8, authorName: '郑十', authorAvatar: '', price: 25.00, originalPrice: 49.00, categoryId: 7, chapterCount: 5, studyCount: 456, estimatedHours: 4.0 }
  ],
  chapters: [
    { id: 1, courseId: 1, title: '第一章：Vue3 入门与环境搭建', sortOrder: 1, wordCount: 1500, isFree: 1, content: '# Vue3 入门与环境搭建\n\n欢迎来到 Vue3 的世界！本章节将带你了解 Vue3 的基本概念，并完成开发环境的搭建。\n\n## 1.1 Vue3 简介\n\nVue.js 是一款用于构建用户界面的渐进式 JavaScript 框架。Vue3 是 Vue.js 的最新版本，引入了许多新特性和改进。\n\n### 主要特性\n\n- 组合式 API：提供更灵活的代码组织方式\n- 响应式系统重构：使用 Proxy 替代 Object.defineProperty\n- 更好的 TypeScript 支持：原生支持 TypeScript\n- 性能提升：更快的渲染速度和更小的打包体积\n\n## 1.2 环境搭建\n\n首先需要安装 Node.js，建议使用 LTS 版本。\n\n使用 Vue CLI 创建项目，按照提示选择项目配置，完成后进入项目目录并安装依赖。\n\n## 1.3 第一个 Vue3 应用\n\n创建一个简单的 Hello World 应用，恭喜你！你已经成功创建了第一个 Vue3 应用。' },
    { id: 2, courseId: 1, title: '第二章：组合式 API 核心概念', sortOrder: 2, wordCount: 1200, isFree: 1, content: '# 组合式 API 核心概念\n\n组合式 API 是 Vue3 最重要的特性之一，它提供了一种更灵活的代码组织方式。\n\n## 2.1 setup 函数\n\nsetup 函数是组合式 API 的入口，在这里编写组合式 API 代码。\n\n## 2.2 ref 和 reactive\n\nref 用于创建响应式的基本类型数据，reactive 用于创建响应式的对象。\n\n## 2.3 computed\n\ncomputed 用于创建计算属性，可以根据依赖自动更新。' },
    { id: 3, courseId: 1, title: '第三章：响应式系统深入理解', sortOrder: 3, wordCount: 1400, isFree: 0, content: '# 响应式系统深入理解\n\nVue3 的响应式系统是其核心特性之一，理解它的工作原理对于编写高效的代码至关重要。\n\n## 3.1 Proxy 原理\n\nVue3 使用 ES6 的 Proxy 对象来实现响应式，通过 get 和 set 拦截实现依赖收集和触发更新。\n\n## 3.2 依赖收集与触发\n\ntrack 函数负责收集依赖，将当前的 effect 添加到依赖集合中。trigger 函数负责触发更新，遍历依赖集合并执行所有 effect。\n\n## 3.3 effect 和 watch\n\neffect 用于创建副作用函数，watch 用于监听响应式数据的变化。' },
    { id: 4, courseId: 1, title: '第四章：组件通信', sortOrder: 4, wordCount: 1100, isFree: 0, content: '# 组件通信\n\n在 Vue3 中，组件之间的通信方式有多种，每种方式适用于不同的场景。\n\n## 4.1 Props\n\nProps 是父组件向子组件传递数据的主要方式，子组件通过 defineProps 接收。\n\n## 4.2 Emits\n\nEmits 是子组件向父组件发送事件的方式，子组件通过 defineEmits 定义事件。\n\n## 4.3 provide 和 inject\n\nprovide 和 inject 用于跨层级组件通信，父组件提供数据，后代组件可以注入使用。' },
    { id: 5, courseId: 1, title: '第五章：路由与状态管理', sortOrder: 5, wordCount: 1000, isFree: 0, content: '# 路由与状态管理\n\n在大型应用中，路由和状态管理是必不可少的。\n\n## 5.1 Vue Router\n\nVue Router 是 Vue 官方的路由管理器，支持多种路由模式和导航守卫。\n\n## 5.2 Pinia\n\nPinia 是 Vue 官方推荐的状态管理库，提供简洁的 API 和良好的 TypeScript 支持。' },
    { id: 6, courseId: 1, title: '第六章：组合式函数', sortOrder: 6, wordCount: 900, isFree: 0, content: '# 组合式函数\n\n组合式函数是 Vue3 中组织逻辑的一种方式，它允许你将可复用的逻辑提取到函数中。\n\n## 6.1 什么是组合式函数\n\n组合式函数是一个使用 Vue 组合式 API 的函数，它返回一组响应式状态和方法。\n\n## 6.2 创建组合式函数\n\n通过 ref、onMounted、onUnmounted 等 API 创建可复用的组合式函数。\n\n## 6.3 使用组合式函数\n\n在组件中调用组合式函数，获取返回的响应式状态和方法。' },
    { id: 7, courseId: 1, title: '第七章：实战项目开发', sortOrder: 7, wordCount: 800, isFree: 0, content: '# 实战项目开发\n\n通过一个完整的实战项目，将所学知识应用到实际开发中。\n\n## 7.1 项目规划\n\n在开始开发之前，需要进行项目规划：需求分析、技术选型、架构设计、任务分解。\n\n## 7.2 项目结构\n\n合理的项目结构有助于代码组织和维护，包括 components、views、stores、router 等目录。\n\n## 7.3 开发流程\n\n按照创建项目基础结构、实现组件、配置路由、实现状态管理、测试与优化的流程进行开发。' },
    { id: 8, courseId: 1, title: '第八章：性能优化与最佳实践', sortOrder: 8, wordCount: 700, isFree: 0, content: '# 性能优化与最佳实践\n\n学习 Vue3 的性能优化技巧和最佳实践，让你的应用更加高效。\n\n## 8.1 性能优化技巧\n\n使用 v-memo 缓存模板片段，使用 shallowRef 和 shallowReactive 处理不需要深度响应式的数据。\n\n## 8.2 最佳实践\n\n1. 使用组合式 API 组织代码\n2. 合理使用计算属性\n3. 避免在模板中使用复杂表达式\n4. 使用 v-for 时添加 key\n5. 按需引入组件' }
  ]
}